language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t abdallazaki/docker-react -f Dockerfile.dev .


scripts:
  - docker run abdallazaki/docker-react npm run test -- --coverage --watchAll=false